name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: pwsh
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build src --configuration Release
      - name: Publish artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: nugets
          path: nugets/*
          retention-days: 1
      # - name: Deploy
      #   # Does not follow standard practice of targeting explicit versions because configuration is tightly coupled to Octopus Deploy configuration
      #   uses: Particular/push-octopus-package-action@main
      #   with:
      #     octopus-deploy-api-key: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
